# Generated by Django 3.2.25 on 2025-06-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=40)),
                ('releasedate', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
