# Generated by Django 3.2.25 on 2025-06-25 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='movies',
            new_name='Movie',
        ),
    ]
