# Generated by Django 3.2.25 on 2025-06-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0002_rename_movies_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='hero',
            field=models.CharField(default='Unknown Hero', max_length=100),
        ),
    ]
