# Generated by Django 3.2.25 on 2025-06-30 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0003_movie_hero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='hero',
        ),
    ]
