# Generated by Django 3.2.25 on 2025-07-06 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0005_movie_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='poster',
        ),
    ]
